### ISSUE TITLE
skip / filter

### ISSUE THREAD

**Issue by elrumordelaluz** [ravangen/graphql-rate-limit#113]
Hi @ravangen, thanks for this useful library.

I am wondering if there is a way to set a `skip` (or `filter`) logic like in [this library](https://github.com/nfriedly/express-rate-limit#skip). 

Probably I could set something through `onLimit` but I think is too late, since the key was already stored/accumulated.

Thanks!

**Comment by ravangen** [comment]
Hey @elrumordelaluz,

Thanks for the suggestion! I would like to explore your use case further to support you. I assume you are looking to do this check per field instead of once across the entire request?

I have a new feature in progress that may be of use here. Currently the cost is assumed to be `1` for each field occurrence. I am exploring adding a `calculatePoints` function (receives data like resolver `args` and `context`) that would determine what the cost should be given some conditions. I think `skip` could be accomplished by having such a function return a cost of `0`.

Let me know what you think

**Comment by ravangen** [comment]
Hi @elrumordelaluz,

I have released [version 1.2.0](https://github.com/ravangen/graphql-rate-limit/blob/master/CHANGELOG.md#120--2019-09-29) which includes a [`pointsCalculator`](https://github.com/ravangen/graphql-rate-limit#pointscalculator) option so you can specify how to determine the cost. If this function returns `0`, then it has the effect of skipping limiting that field. I have included a [points example](https://github.com/ravangen/graphql-rate-limit/tree/master/examples/points) that can demonstrate some potential applications of this feature.

Give it a go and would love some feedback 😄
