### ISSUE TITLE
Stacked rate limit gets exhausted while another rate is still in play

### ISSUE THREAD

**Issue by ArtS** [ravangen/graphql-rate-limit#129]
Using this example (https://github.com/ravangen/graphql-rate-limit/blob/master/examples/multiple/index.js) I built an app that has two rate limits on an endpoint:

- 10 requests per minute
- 30 requests per half an hour

When first rate limit gets exhausted,  second rate limit still seems to get its counter increased even though user's requests are not being served and error is returned.

In more plain terms, if I hit the endpoint in first 2 minutes with 31 request, I get blocked for half an hour, although out of those 31 requests only 10 should have been contributing towards the increase of the counter in the second rate limiter.

I hope this makes sense.

**Comment by ravangen** [comment]
Hi @ArtS,

The rate limits are independent of each other, and are evaluated from right to left. Each additional directive wraps the previous ones. There is currently no exposed way for different limiters to communicate to each other and refund past consumed points that still resulted in a limit error.

I will update the example you linked, so that `@sustainedRateLimit` is defined first and evaluated after `@burstRateLimit`. This isn't perfect still. Consider when `burstRateLimit` passes, `sustainedRateLimit` may return an error and not refund the already consumed `burstRateLimit`.

```graphql
    books: [Book!]
      @sustainedRateLimit(limit: 3, duration: 60)
      @burstRateLimit(limit: 1, duration: 15)
```

Example
- _t=0s_: One request, uses `burstRateLimit` remaining 0 and `sustainedRateLimit` remaining 2
- _t=10s_: One request, errors due to `burstRateLimit`, `sustainedRateLimit` not run (remaining 2)
- _t=15s_: `burstRateLimit` limit restored (remaining 1)
- _t=20s_: One request, `burstRateLimit` remaining 0 and `sustainedRateLimit` remaining 1
- _t=35s_: `burstRateLimit` limit restored (remaining 1)
- _t=40s_: One request, `burstRateLimit` remaining 0 and `sustainedRateLimit` remaining 0
- _t=55s_: `burstRateLimit` limit restored (remaining 1)
- _t=56s_: One request, `burstRateLimit` remaining 0, errors due to `sustainedRateLimit`
- _t=57s_: One request, errors due to `burstRateLimit`, `sustainedRateLimit` not run (remaining 0)
- _t=60s_: `sustainedRateLimit` limit restored (remaining 3)
- _t=71s_: `burstRateLimit` limit restored (remaining 1)
