### ISSUE TITLE
feat: error handler to determine error action and returned data

### ISSUE THREAD

**Issue by shellscape** [ravangen/graphql-rate-limit#29]
You've done some great work here, and the module works flawlessly. 👏 

I'm familiar with your sibling here: https://www.npmjs.com/package/graphql-rate-limit, which has an option that allows one to `formatError`. While useful to a cosmetic degree, it's still not flexible and throws an error (albeit throwing a GraphQLError is the right choice, so kudos).  What I have in mind is a little more control. Our server setup is such that even when critical errors occur, we send a result, and in the case of an error a simple object of `{ error: String }`. The reasons are many, and while slightly outside of the norm for GraphQL, this works best for us.

My proposal:

```js
const schemaDirectives = {
  rateLimit: createRateLimitDirective({
    onFailure: ({ location, message, path }) => {
      return {
        error: message
      };
    }
  })
};
```

Of course `onFailure` is merely a semantic suggestion and any name there would be good. But the idea is that instead of the resolver wrapper throwing an error, an option allows us to specify a function that can optionally return data to the client instead of throwing. This option could also potentially allow for mutating the location, message, or path as well but I would leave that up to you to decide upon.

Hopefully this is well received and something you're open to.

**Comment by ravangen** [comment]
Hi, thanks for the great feedback!

I cannot take any credit for [`graphql-rate-limit`](https://www.npmjs.com/package/graphql-rate-limit) although have provided them some feedback based on my learning writing my own version. They beat me to the publishing of a package 😄 

I think the functionality you describe may already be offered, although under a different name ([`throttle`](https://github.com/ravangen/graphql-rate-limit/blob/db13230656ddd39f0d1a6cb95587c111c81b0e4c/src/index.ts#L41) instead of `onFailure`). I had a hard time naming it, and do like the suggestion.

The [Throttle Behaviour](https://github.com/ravangen/graphql-rate-limit#throttle-behaviour) section is brief, but the [throttle object example](https://github.com/ravangen/graphql-rate-limit/tree/master/examples/throttle-object) may better clarify how to accomplish your requirements.

For example
```typescript
const throttle = (resource, directiveArgs, source, args, context, info) =>
  ({
    error: `Too many requests, please try again in ${Math.ceil(resource.msBeforeNext / 1000)} seconds.`
  });
```

Please let me know how that works out for you

**Comment by shellscape** [comment]
That's exactly what I was looking for, thank you. Naming is hard - no worries. As an aside, it might be helpful for folks to have a more defined API reference, with listed options for the exported methods for the module.
